/**
 * Installing and listing what the catalogue offers.
 *
 * Two kinds of bundle, told apart by their contents rather than by where they sit: a plugin is a
 * directory of skills, and an MCP bundle is a directory whose whole content is a server
 * declaration. Installing the second writes its servers into settings, which is the only place a
 * session reads them from — that is what stops the same server existing twice, once here and once
 * on the MCP settings page, with two switches that could not see each other.
 */

import { ipcMain, shell } from "electron";
import { mkdir, rename } from "node:fs/promises";
import { basename, join } from "node:path";
import type { McpBundle, Settings } from "@lyra/core";
import { lyraHome, fetchRegistry, installEntry, loadPlugins, loadSkills, uninstallEntry } from "@lyra/core";
import { remoteImage } from "../avatars.ts";
import type { RegistryEntry } from "../ipc-types.ts";

/*
 * How long an index is reused without asking again.
 *
 * The catalogue is a JSON file regenerated by a scheduled job once a day, so re-fetching it every
 * time the view mounts buys nothing and costs a visible reload: leave the page and come back and
 * the shop empties and refills in front of you. Fifteen minutes is far shorter than the thing
 * changes and far longer than a browsing session, and 刷新 ignores it entirely.
 */
const INDEX_CACHE_MS = 15 * 60 * 1000;

/** Per URL, so one slow or broken registry does not invalidate the others. */
const indexes = new Map<string, { at: number; registry: Awaited<ReturnType<typeof fetchRegistry>> }>();

export interface PluginsIpcDeps {
	settings(): Settings;
	saveSettings(next: Settings): Promise<unknown>;
}

export function registerPluginsIpc({ settings, saveSettings }: PluginsIpcDeps): void {
	const disabledPlugins = () => settings().disabledPlugins;
	ipcMain.handle("registry:fetch", async (_event, url: string, force?: boolean) => {
		const hit = indexes.get(url);
		if (!force && hit && Date.now() - hit.at < INDEX_CACHE_MS) {
			return { ok: true as const, registry: hit.registry };
		}
		try {
			const registry = await fetchRegistry(url);
			indexes.set(url, { at: Date.now(), registry });
			return { ok: true as const, registry };
		} catch (cause) {
			/*
			 * A failed refresh falls back to what we last had, rather than to nothing.
			 *
			 * The index is a daily-synced file; the copy from an hour ago is almost certainly still
			 * true, and it is unquestionably more useful than an empty shop with an error on it.
			 * Only a first fetch with nothing behind it has to report the failure.
			 */
			if (hit) return { ok: true as const, registry: hit.registry };
			return { ok: false as const, message: cause instanceof Error ? cause.message : String(cause) };
		}
	});

	/*
	 * Cloning is a write to disk from a URL the user typed, so it says what it did.
	 *
	 * A plugin is inert until the loader picks it up on the next session. An MCP bundle takes one
	 * step more: its servers are merged into settings, where the MCP page can show them, the user
	 * can point Filesystem at the right directory, and the session will actually connect to them.
	 * They arrive switched off — installing is not the same as trusting, and a server is a command
	 * that runs on this machine with this user's permissions.
	 */
	ipcMain.handle("registry:install", async (_event, entry: RegistryEntry, registryName?: string) => {
		try {
			const installed = await installEntry(entry, registryName);
			if (installed.kind === "mcp" && installed.servers.length > 0) {
				const current = settings();
				// Re-installing something replaces its servers rather than doubling them up.
				const others = current.mcpServers.filter((server) => server.origin?.bundle !== entry.id);
				await saveSettings({
					...current,
					mcpServers: [...others, ...installed.servers.map((server) => ({ ...server, enabled: false }))],
				});
			}
			return { ok: true as const, dir: installed.dir, kind: installed.kind, servers: installed.servers.length };
		} catch (cause) {
			return { ok: false as const, message: cause instanceof Error ? cause.message : String(cause) };
		}
	});

	/*
	 * Removing the directory is only half of it.
	 *
	 * An MCP bundle left rows behind in settings; leaving them there would keep a server the user
	 * just uninstalled in the list, still connectable, pointing at a command that is no longer on
	 * disk. `origin.bundle` is what ties the two together.
	 */
	ipcMain.handle("registry:uninstall", async (_event, id: string) => {
		await uninstallEntry(id);
		const current = settings();
		const remaining = current.mcpServers.filter((server) => server.origin?.bundle !== id);
		if (remaining.length !== current.mcpServers.length) {
			await saveSettings({ ...current, mcpServers: remaining });
		}
	});

	/**
	 * Bring what is on disk and what is in settings back into agreement.
	 *
	 * Every MCP bundle installed before the split went into `~/.lyra/plugins` and was loaded
	 * through the plugin's own `mcpServers` list — a path that no longer exists. Left alone, an
	 * upgrade would silently disconnect every MCP server anybody had installed: still on disk,
	 * still in the catalogue, connected to nothing.
	 *
	 * So anything on disk without a matching row gets one. It keeps the state it had, which for a
	 * bundle loaded the old way means "on unless the user switched this plugin off" — a migration
	 * that turns working servers off is as wrong as one that turns unknown servers on. Idempotent:
	 * the second call finds a row for everything and writes nothing.
	 */
	const reconcile = async (bundles: McpBundle[]): Promise<void> => {
		const current = settings();
		const known = new Set(current.mcpServers.map((server) => server.origin?.bundle).filter(Boolean));
		const missing = bundles.filter((bundle) => !known.has(bundle.id));
		if (missing.length === 0) return;

		const disabled = new Set(current.disabledPlugins);
		const restored = missing.flatMap((bundle) =>
			bundle.servers.map((server) => ({
				...server,
				enabled: !disabled.has("*") && !disabled.has(bundle.id),
			})),
		);
		await saveSettings({ ...current, mcpServers: [...current.mcpServers, ...restored] });
	};

	/**
	 * Move a bundle to the directory its kind belongs in.
	 *
	 * Cosmetic, deliberately: sorting reads the contents, so a bundle in the wrong place already
	 * works. This only keeps the two directories meaning what their names say, and a failure is
	 * ignored for exactly that reason — there is nothing to recover from.
	 */
	const tidy = async (bundles: McpBundle[]): Promise<void> => {
		const home = join(lyraHome(), "mcp");
		for (const bundle of bundles) {
			if (bundle.source !== "user" || bundle.dir.startsWith(home)) continue;
			await mkdir(home, { recursive: true }).catch(() => {});
			await rename(bundle.dir, join(home, basename(bundle.dir))).catch(() => {});
		}
	};

	ipcMain.handle("plugins:list", async (_event, cwd: string) => {
		const [plugins, skills] = await Promise.all([
			loadPlugins(
				[
					...(cwd ? [{ dir: join(cwd, ".lyra", "plugins"), source: "workspace" as const }] : []),
					{ dir: join(lyraHome(), "plugins"), source: "user" as const },
					// Both roots, because a bundle is sorted by what it holds — one installed before
					// the split is still filed under `plugins` and still has to come back as MCP.
					{ dir: join(lyraHome(), "mcp"), source: "user" as const },
				],
				disabledPlugins(),
			),
			loadSkills([
				...(cwd ? [{ dir: join(cwd, ".lyra", "skills"), source: "workspace" as const }] : []),
				{ dir: join(lyraHome(), "skills"), source: "user" as const },
			]),
		]);
		/*
		 * Done on the way out of a read, which is not where side effects usually belong.
		 *
		 * The alternative is a migration at startup, and this page is reached before the first
		 * session exists — someone opening 设置 › MCP on a fresh launch would see an empty list
		 * and conclude their servers were gone. Both are idempotent and both no-op once there is
		 * nothing left to fix, so the cost of running them here is a comparison per scan.
		 */
		await reconcile(plugins.mcpBundles);
		void tidy(plugins.mcpBundles);

		const looseNames = new Set(skills.skills.map((skill) => skill.name));
		return {
			plugins: plugins.plugins,
			mcpBundles: plugins.mcpBundles,
			pluginDiagnostics: plugins.diagnostics,
			skills: [
				...skills.skills,
				...plugins.plugins
					.filter((plugin) => plugin.enabled)
					.flatMap((plugin) => plugin.skills)
					.filter((skill) => !looseNames.has(skill.name)),
			],
			skillDiagnostics: skills.diagnostics,
		};
	});

	/*
	 * Icons, fetched here so the page's Content-Security-Policy does not have to open up.
	 *
	 * A registry entry's logo is a URL from a file we did not write. `img-src` is narrow on purpose,
	 * and widening it to the whole web so a 36px tile can render would trade a real boundary for a
	 * decoration. Cached, so a list of twenty entries is twenty requests once and none after.
	 */
	ipcMain.handle("registry:icon", async (_event, url: string) => remoteImage(url));

	ipcMain.handle("plugins:revealDir", async (_event, scope: "workspace" | "user", cwd: string) => {
		const dir = pluginsDir(scope, cwd);
		await mkdir(dir, { recursive: true });
		await shell.openPath(dir);
		return dir;
	});

}

function pluginsDir(scope: "workspace" | "user", cwd: string): string {
	return scope === "workspace" ? join(cwd, ".lyra", "plugins") : join(lyraHome(), "plugins");
}
